### ISSUE TITLE
work for vgg or googlenet

### ISSUE THREAD

**Issue by sunbaigui** [piergiaj/caffe-deconvnet#1]
wow, great work, visualize model is very important for tunning model.
does this also work for vgg and googlenet?

**Comment by piergiaj** [comment]
It should. You will have to make some modifications to the vgg and googlenet proto files to collect the switch variables from the pooling layers and you will have to create the proto file for the DeconvNet, just like the example for AlexNet. After that, it should work.

**Comment by shi69** [comment]
Thanks for the work, and it works well on AlexNet. So then I replaced the vgg proto file with the following for pooling layer 1 (numbers changed based on layer #). However python will die unexpectedly when I load the modified vgg model (not yet try the inverse net)...Am I doing something wrong here? 

...
...
layer {  
  name: "pool1"
  type: "PoolingSwitches"
  bottom: "conv1_2"
  top: "poolswitches1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
layer {  
  name: "slice1"
  type: "SliceHalf"
  bottom: "poolswitches1"
  top: "pool1"
  top: "switches1"
  slice_param {
      axis: 0
  }
}
...
...

**Comment by piergiaj** [comment]
I'm not sure, it looks correct to me. However, it is worth noting that the PoolingSwitches layer and the SliceHalf layer are actually not needed to perform this. I recently discovered that Caffe's Pooling layer will output the switch values when given two tops. All that is really needed is the UnPooling layer. For example:

```
layer {
  name: "pool"
  type: "Pooling"
  bottom: "conv1"
  top: "pool1"
  top: "switch1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}


layer {
  name: "unpool1"
  type: "UnPooling"
  bottom: "pool1"
  bottom: "switch1"
  top: "unpool1"
  pooling_param {
    pool: MAX
    kernel_size: 2
    stride: 2
  }
}
```

I have some updated versions of this code, that I will be pushing soon.

**Comment by mollyStark** [comment]
@piergiaj @sunbaigui Hi,I tried to use this for googlenet, but I noticed that googlenet use avg pool rather than max pool, is the switch pool uppooling method fit for the avg pool layer?
